# Generated by Django 3.1.3 on 2021-05-12 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelZones',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post_codes', models.CharField(default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelzones_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelzones_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelzones_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel_zones',
            },
        ),
        migrations.CreateModel(
            name='ParcelWeightClasses',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelweightclasses_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelweightclasses_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelweightclasses_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel_weight_class',
            },
        ),
        migrations.CreateModel(
            name='ParcelServices',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelservices_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelservices_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelservices_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel_services',
            },
        ),
        migrations.CreateModel(
            name='ParcelSalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_number', models.PositiveIntegerField()),
                ('courier', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelsaleprice_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelsaleprice_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.parcelservices')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelsaleprice_updated_set', to=settings.AUTH_USER_MODEL)),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.parcelweightclasses')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.parcelzones')),
            ],
            options={
                'db_table': 'parcel_sale_price',
            },
        ),
        migrations.CreateModel(
            name='ParcelCostPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('courier', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelcostprice_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelcostprice_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.parcelservices')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_parcelcostprice_updated_set', to=settings.AUTH_USER_MODEL)),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.parcelweightclasses')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.parcelzones')),
            ],
            options={
                'db_table': 'parcel_cost_price',
            },
        ),
        migrations.AddIndex(
            model_name='parcelzones',
            index=models.Index(fields=['id'], name='dc_zone_id_index'),
        ),
        migrations.AddIndex(
            model_name='parcelweightclasses',
            index=models.Index(fields=['id'], name='dc_weight_class_id_index'),
        ),
        migrations.AddIndex(
            model_name='parcelservices',
            index=models.Index(fields=['id'], name='dc_service_id_index'),
        ),
        migrations.AddIndex(
            model_name='parcelsaleprice',
            index=models.Index(fields=['client_number'], name='dc_sale_client_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelsaleprice',
            index=models.Index(fields=['courier'], name='dc_sale_courier_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelcostprice',
            index=models.Index(fields=['courier'], name='dc_cost_courier_idx'),
        ),
    ]
