# Generated by Django 3.1.3 on 2021-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoice_invoicenumbersequence_surchargerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='surchargerate',
            name='original_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
