# Generated by Django 3.1.3 on 2021-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_surchargerate_original_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelcostprice',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='parcelsaleprice',
            name='zone',
        ),
        migrations.AddField(
            model_name='parcelcostprice',
            name='zone_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcelsaleprice',
            name='zone_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
