# Generated by Django 3.1.3 on 2022-02-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=12)),
                ('posttown', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=24)),
                ('locality', models.CharField(max_length=32)),
                ('house_name', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=32)),
                ('admin_county', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postcode'], name='addresses_postcod_55d368_idx'),
        ),
    ]
